student@guithi0777-server:~/ansible-test$ cat ansible/playbooks/recette.yml
---
name: Deploy Ansible playbooks
on: 
   push:
      branches:

           - main 

jobs:
  run-ansible:
   runs-on: self-hosted
   
   steps:
   
       - name: Check Out Repository
         uses: actions/checkout@v4

       - name: copy ansible file
         run: |
           rsync -av -P ansible /home/student ansible-playbook -i etc/hosts ansible/playbooks/recette.yml
